### ISSUE TITLE
bulutfon organization hesabı

### ISSUE THREAD

**Issue by dnomak** [bulutfon/documents#11]
bulutfon neden kişi olarak görüntüleniyor organization hesabına geçirmemenizin özel bir sebebi var mı ?

**Comment by onurozgurozkan** [comment]
Bariz bir nedeni yok. Gerek görmedik. Diğer bir konuda codereview süreçlerimizi pull request ile çözmemizden kaynaklanıyor. :)

**Comment by dnomak** [comment]
anladım teşekkür ederim :)

**Comment by onurozgurozkan** [comment]
@dnomak biz teşekkür ederiz. :)
