### ISSUE TITLE
CDR Endpoint Eksik Key Değerleri

### ISSUE THREAD

**Issue by aliemre** [bulutfon/documents#5]
Merhabalar. CDR kayıtlarını alırken **extension** ve **call_price** key değeri dönmüyor. Acaba API de bir sorun mu var yoksa olmadığı için objeye dahil edilmiyor mu?

``` php
object(stdClass)#18 (11) {
    ["uuid"]=>
    string(36) "53b6a736-1f80-11e5-b830-153874dc4b39"
    ["bf_calltype"]=>
    string(5) "voice"
    ["direction"]=>
    string(2) "IN"
    ["caller"]=>
    int(905468202054)
    ["callee"]=>
    int(908508851063)
    ["call_time"]=>
    string(25) "2015-07-01T02:40:39+03:00"
    ["answer_time"]=>
    string(25) "2015-07-01T02:40:39+03:00"
    ["hangup_time"]=>
    string(25) "2015-07-01T02:40:50+03:00"
    ["call_record"]=>
    string(3) "Yok"
    ["hangup_cause"]=>
    string(15) "NORMAL_CLEARING"
    ["hangup_state"]=>
    string(8) "recv_bye"
  }
```

**Comment by onurozgurozkan** [comment]
@aliemre Merhaba, gelen aramada tipinde `direction="IN"` ise `extension` ve `call_price` olmuyor diye biliyorum.
- Gelen aramada aramayı bir dahili başlatmadığından ve her zaman bir dahili ile sonlanmadığından 
- Gelen aramanın bir ücreti olmadığından `call_price` alanları gelmiyor.

@hamitturkukaya daha doğru ve açıklayıcı bilgi verebilir. Ben böyle hatırlıyorum ama doğru bilgi olmayabilir. :)

**Comment by hamitturkukaya** [comment]
Merhaba,
Extension ve Call Price sadece giden aramalarda setlenir ve Aramayı başlatan dahiliyi ve dakikalık görüşme ücretini belirtir. Aramanız gelen arama olduğu için bu fieldlar bulunmamakta.

Api dökümanlarında
https://github.com/bulutfon/documents/blob/master/API/endpoints/cdr.md#dönen-değerler
kısmından cdr ve diğer endpointlere ait conditional fieldları inceleyebilirsiniz.

**Comment by aliemre** [comment]
@onurozgurozkan @hamitturkukaya Teşekkür ederim. Bu bilgiler doğrultusunda yazılımımı güncelledim.
